### ISSUE TITLE
oAuth Issue  even though I have authenticated to the Sandbox

### ISSUE THREAD

**Issue by sachinsid** [forcedotcom/dependencies-cli#1]
Hi Andy, 

When I try to run the tool, I get an error "Must pass a username and/or OAuth options when creating an AuthInfo instance.", even though I authenticated directly against the sandbox. Also FYI, it looks like the tool is called 'andyinthecloud' for some reason and not dependency per the wiki, so If I need to run a report, I need to use

sfdx andyinthecloud:dependencies:report. instead of 

sfdx dependency:dependencies:report

Hope you can help...

**Comment by hkache** [comment]
Hi - I have just uploaded a new version of the package (version 2.0.0-beta) where the commands properl resolved to `sfdx dependency:dependencies:report` as documented. Can you please update to that latest version and see if it also fixeds the OAuth problem for you?

**Comment by hkache** [comment]
Upgrade to 2.0.1 will resolve this problem. Closing ...
