### ISSUE TITLE
Getting error when installing dependency plugin

### ISSUE THREAD

**Issue by harshitsinghal** [forcedotcom/dependencies-cli#2]
Please see image below and advise:

![image](https://user-images.githubusercontent.com/5120879/71446448-72c79600-2749-11ea-98c2-b74246bba21b.png)

**Comment by hkache** [comment]
Dear Harshit - I have just update the npm package version from 1.3.0 to 2.0.0-beta. Can you please have a try again and see if that change resolves your install problems?

**Comment by hkache** [comment]
Upgrade to any 2.x.x release will resolve this. The plugin name was changed from 1.x.x and 2.x.x
